//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmActors
    {
        public int FilmId { get; set; }
        public long ActorId { get; set; }
        public string Role { get; set; }
    
        public virtual Actors Actors { get; set; }
        public virtual Films Films { get; set; }
    }
}
