//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Films
    {
        public Films()
        {
            this.FilmActors = new HashSet<FilmActors>();
            this.Sessions = new HashSet<Sessions>();
            this.Genres = new HashSet<Genres>();
            this.ProducingCompanies = new HashSet<ProducingCompanies>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public short Duration { get; set; }
        public string Description { get; set; }
        public byte AgeRestriction { get; set; }
    
        public virtual ICollection<FilmActors> FilmActors { get; set; }
        public virtual ICollection<Sessions> Sessions { get; set; }
        public virtual ICollection<Genres> Genres { get; set; }
        public virtual ICollection<ProducingCompanies> ProducingCompanies { get; set; }
    }
}
