//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public Film()
        {
            this.FilmActors = new HashSet<FilmActor>();
            this.Sessions = new HashSet<Session>();
            this.Genres = new HashSet<Genre>();
            this.ProducingCompanies = new HashSet<ProducingCompany>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public short Duration { get; set; }
        public string Description { get; set; }
        public byte AgeRestriction { get; set; }
    
        public virtual ICollection<FilmActor> FilmActors { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
        public virtual ICollection<ProducingCompany> ProducingCompanies { get; set; }
    }
}
