//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hall
    {
        public Hall()
        {
            this.Seats = new HashSet<Seat>();
        }
    
        public short Id { get; set; }
        public string Name { get; set; }
        public short RowsCount { get; set; }
        public int SeatsCount { get; set; }
    
        public virtual ICollection<Seat> Seats { get; set; }
    }
}
