//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaEntities : DbContext
    {
        public CinemaEntities()
            : base("name=CinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Actors> Actors { get; set; }
        public DbSet<Countries> Countries { get; set; }
        public DbSet<Films> Films { get; set; }
        public DbSet<Genres> Genres { get; set; }
        public DbSet<Halls> Halls { get; set; }
        public DbSet<Posts> Posts { get; set; }
        public DbSet<ProducingCompanies> ProducingCompanies { get; set; }
        public DbSet<Seats> Seats { get; set; }
        public DbSet<Sessions> Sessions { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tickets> Tickets { get; set; }
        public DbSet<Workers> Workers { get; set; }
        public DbSet<FilmActors> FilmActors { get; set; }
    }
}
