//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProducingCompanies
    {
        public ProducingCompanies()
        {
            this.Films = new HashSet<Films>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<short> CountryId { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual ICollection<Films> Films { get; set; }
    }
}
