//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seats
    {
        public Seats()
        {
            this.Bookings = new HashSet<Bookings>();
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int Id { get; set; }
        public short RowNumber { get; set; }
        public int SeatNumber { get; set; }
        public bool IsOccupied { get; set; }
        public short HallId { get; set; }
    
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual Halls Halls { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
