//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        public Sessions()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public long Id { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public int FilmId { get; set; }
    
        public virtual Films Films { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
